---
- hosts: postfix
  gather_facts: no

  vars_prompt:
    - name: hostname
      prompt: "What is the new_hostname? e.g. cpanel.angani.co"
      private: no

    - name: IP_ADDRESS
      prompt: "Enter server IP Address?"
      private: yes
  roles:
    - postfix
