---
#installing cPanel

- name: Download cPanel Installer
  shell: curl -o latest -L https://securedownloads.cpanel.net/latest
  become: true
  register: installer_downloaded

- name: The Installation process
  shell: sh latest
  ignore_errors: true
  become: true
  register: cpanel_installed
  changed_when: cpanel_installed.stdout.find('Congratulations')
  async: 900
  poll: 10
